welcome-message:
  - "&7&l&m----------------------------------------"
  - " "
  - "&fWelcome to &cPractice Club&f!"
  - " "
  - "&f🞮 &cWebsite: &fwww.practiceclub.us"
  - "&f🞮 &cStore: &fwww.practiceclub.us/store"
  - " "
  - "&7&l&m----------------------------------------"